name: Release Files

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # get part of the tag after the `v`
    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Artifact download
      uses: actions/download-artifact@v2
      with:
        name: traefik
        path: ${{ github.workspace }}/traefik

    # Create a zip file with all files required by the module to add to the release
    - run: zip -r ${{ github.workspace }}/traefik_linux_amd64_${{steps.get_version.outputs.version-without-v}}.zip ${{ github.workspace }}/traefik

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ github.workspace }}/traefik_linux_amd64_${{steps.get_version.outputs.version-without-v}}.zip
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}